# Generated by Django 4.2.20 on 2025-03-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('driverName', models.CharField(max_length=100)),
                ('trailerNumber', models.IntegerField()),
                ('truckNumber', models.IntegerField()),
                ('homeTerminal', models.TextField()),
                ('mainOfficeAddress', models.TextField()),
                ('carrierName', models.CharField(max_length=100)),
                ('milesDriven', models.TextField()),
                ('shipperCommodity', models.TextField()),
                ('totalMileage', models.TextField()),
                ('remarks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LocationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('currentLocation', models.TextField()),
                ('pickupLocation', models.TextField()),
                ('dropoffLocation', models.TextField()),
                ('currentcyclic', models.CharField(choices=[('70 Hour / 8 Day', '70'), ('60 Hour / 7 Day', '60')], default='70', max_length=20)),
            ],
        ),
    ]
